<Project>

  <PropertyGroup>
    <!-- Cumplimiento estricto de estilo de código y analizadores de Roslyn en compilación -->
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- Reglas de solo aviso (no rompen la compilación): sugerencias de readonly -->
    <WarningsNotAsErrors>$(WarningsNotAsErrors);IDE0044;IDE0250;IDE0251</WarningsNotAsErrors>

    <!-- Escáner de seguridad NuGet activado en modo estricto -->
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <WarningsAsErrors>$(WarningsAsErrors);NU1901;NU1902;NU1903;NU1904</WarningsAsErrors>
  </PropertyGroup>

</Project>
