name: Publicar Paquetes en NuGet

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Determinar versión
      run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

    - name: Restaurar dependencias
      run: dotnet restore ./JCarrillo.AOT.Net.Socket/JCarrillo.AOT.Net.Socket.csproj -p:Version=${{ env.VERSION }}

    - name: Empaquetar Librerías
      run: dotnet pack ./JCarrillo.AOT.Net.Socket/JCarrillo.AOT.Net.Socket.csproj -c Release --no-restore -o ./artifacts -p:Version=${{ env.VERSION }}

    - name: NuGet login (OIDC -> temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: JCarrillo

    - name: Subir paquetes a NuGet
      run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate